### ISSUE TITLE
Compilation issues when using cuda_tensor

### ISSUE THREAD

**Issue by sjdrc** [lgarithm/stdtensor#19]
If I try and include the std_cuda_tensor.hpp header then I get errors like
```
error: ‘rank_t’ has not been declared
error: ‘shape’ does not name a type
error: class ‘basic_cuda_tensor<R, r>’ does not have any field named ‘shape_’
```
If I include the headers like this then it solves the issue. I think this is because the code in ```std_cuda_tensor.hpp``` isn't in the ttl::internal namespace.
```
#include <ttl/tensor>
using rank_t = ttl::internal::rank_t;
template <rank_t r> using shape = ttl::internal::basic_shape<r>;
#include <ttl/bits/std_cuda_tensor.hpp>
```

adding ```#define TRACE(x) return;``` before the import fixes the issue.

**Comment by lgarithm** [comment]
The cuda_tensor is not officially supported yet, it's not in the public API.

**Comment by sjdrc** [comment]
Thanks very much for pushing the fixes :)

I saw that it wasn't in the public API, but in our re-implementation of OpenPose+ I'd rather just use one library for managing the tensors and not have to include our own cuda_tensor class.
