### ISSUE TITLE
taking slices of a tensor

### ISSUE THREAD

**Issue by sjdrc** [lgarithm/stdtensor#23]
I have the following tensor defined (in CHW order)
```
ttl::tensor<float, 3> t(57, 52, 52)
```
I want to convert this into two separate tensors, with shapes (19, 52, 52) and (38, 52, 52). What would be the best way to achieve this? Thanks for your help.

**Comment by lgarithm** [comment]
```cpp
    const auto t1 = t.slice(0, 19);
    const auto t2 = t.slice(19, 57);
```

**Comment by sjdrc** [comment]
Legend!
