### ISSUE TITLE
reshape APIs

### ISSUE THREAD

**Issue by lgarithm** [lgarithm/stdtensor#41]
- [x] flatten
- [x] chunk

**Comment by sjdrc** [comment]
Hi, what's the roadmap for completing this? Is there anything I can do to help out?

**Comment by lgarithm** [comment]
The `chunk` API is currently implemented here: 
https://github.com/lgarithm/nn-graph-experimental/blob/preview/include/nn/bits/ops/chunk.hpp, 
I will polish it before moving into this repo.
